name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with: { node-version: "22" }
        
      - name: Cache npm
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
        continue-on-error: false

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test --if-present

      - name: Build application
        run: npm run build

      - name: Security audit
        run: npm audit --audit-level high
        continue-on-error: false
      
      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
