name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: "22" }
        
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: false

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test --if-present

      - name: Security audit
        run: npm audit --audit-level high
        continue-on-error: false
      
      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
